language: node_js
node_js:
- "stable"
env:
global:
- export NODE_ENV=test
- cfec62a16f5f88c8ddda45a173cc39f0d906412bdcce7016495706e7e29734c9
before_script:
- npm install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm test
- npm run coverage
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coveralls