env:
  global:
    - CC_TEST_REPORTER_ID=cfec62a16f5f88c8ddda45a173cc39f0d906412bdcce7016495706e7e29734c9
language : node_js
node_js: 'stable'

before_script:
  - npm install -g codeclimate-test-reporter
  

script:
  - nyc --reporter=lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
